VisualText/vscode-nlp

syntaxes/nlp.tmLanguage.json

Added the extension *.pat to the legal files.

VSCODE-NLP-001

---

.vscode/tasks.json
package.json
src/command.js
src/command.ts
src/extension.js
src/extension.ts
syntaxes/nlp.tmLanguage.json
tsconfig.json

Signed-off-by: David de Hilster <dehilster@gmail.com>

VSCODE-NLP-002 add tasks and command palette stub

---

package.json

Signed-off-by: ddehilster <dehilster@gmail.com>

VSCODE-NLP-005 syntax error in package.json

---

nlp-configuration.json
package.json
syntaxes/nlp.tmLanguage.json

Signed-off-by: ddehilster <dehilster@gmail.com>

VSCODE-NLP-006 big fix to syntax colorizer and misc

---

out/analyzerSequence.js
src/analyzerSequence.ts

VSCODE-NLP-011 path to fspath simplification

---

out/analyzerSequence.js
package.json
src/analyzerSequence.ts

VSCODE-NLP-014 fixed spurious text during highlighting - other fixes

---

out/analyzerSequence.js
package.json
src/analyzerSequence.ts

VSCODE-NLP-015 Add refresh all to the analyzer sequence pane

---

out/analyzerSequence.js
package.json
src/analyzerSequence.ts

VSCODE-NLP-016 add functionality to move sequence file up and down

---

out/analyzerSequence.js
src/analyzerSequence.ts

VSCODE-NLP-017 Enhancing the analyzer sequence code

---

out/analyzerSequence.js
package.json
src/analyzerSequence.ts

VSCODE-NLP-020 fixed click on file to open and move bug

---

out/analyzerSequence.js
package.json
src/analyzerSequence.ts

VSCODE-NLP-022 Added delete and insert existing pass file

---

out/analyzerSequence.js
package.json
src/analyzerSequence.ts

VSCODE-NLP-023 Added functionality to add a new pass

---

out/analyzerSequence.js
out/command.js
out/extension.js
package.json
src/analyzerSequence.ts
src/command.ts
src/extension.ts
src/logfile.ts
src/sequence.ts

VSCODE-NLP-024 View Rule Fired, Created classes for sequence and logs

---

out/command.js
package.json
src/command.ts
src/logfile.ts
src/textFile.ts

VSCODE-NLP-025 Add view tree of selected text

---

.vscode/settings.json
package.json
snippets/nlp.json
syntaxes/nlp.tmLanguage.json
syntaxes/tree.tmLanguage.json

VSCODE-NLP-028 Snippets and custom colorization

---

package.json
src/analyzerSequence.ts
src/command.ts
src/logfile.ts
src/sequence.ts
src/textFile.ts

VSCODE-NLP-029 Added reformat rule and major class file reorge

---

package.json
src/analyzer.ts
src/analyzerSequence.ts
src/command.ts
src/logfile.ts
src/nlp.ts
src/sequence.ts
src/textFile.ts

VSCODE-NLP-031 Added an Nlp and Analyzer class

---

src/analyzer.ts
src/settings.ts
src/textFile.ts
src/visualText.ts

VSCODE-NLP-033 Fix nlp call & write current analyzer & text to state.json

---

package.json
src/analyzerView.ts
src/dirfuncs.ts
src/extension.ts
src/outputView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-037 Added outputView and open text on textView title bar

---

package.json
src/analyzer.ts
src/analyzerView.ts
src/dirfuncs.ts
src/logfile.ts
src/sequence.ts
src/sequenceView.ts
src/textFile.ts
src/textView.ts

VSCODE-NLP-038 Added create new analyzer & textview editing capabilities

---

package.json
src/analyzer.ts
src/command.ts
src/nlp.ts
src/outputView.ts
src/textView.ts

VSCODE-ECL-039 Removed log files from TextView

---

fileicons/images/dark/run.svg
fileicons/images/light/run.svg
package.json
src/analyzer.ts
src/analyzerView.ts
src/extension.ts
src/nlp.ts
src/outputView.ts
src/sequenceView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-040 Fixing and improving run

---

src/analyzer.ts
src/extension.ts
src/status.ts
src/textView.ts

VSCODE-NLP-041 Added status bar

---

package.json
src/findFile.ts
src/findView.ts
src/textFile.ts
src/textView.ts

VSCODE-NLP-045 Made text search recursive and added to TextView

---

package.json
src/analyzer.ts
src/command.ts
src/logfile.ts
src/outputView.ts
src/sequence.ts
src/status.ts
src/textFile.ts
src/textView.ts

VSCODE-NLP-048 view rule fired or highlighted text

---

README.md

VSCODE-NLP-050 Filling out the rest of the readme file

---

package.json
src/analyzer.ts
src/analyzerView.ts
src/dirfuncs.ts
src/visualText.ts

VSCODE-NLP-052 Copy analyzer folder for new analyzer

---

src/analyzer.ts
src/dirfuncs.ts
src/jsonState.ts
src/nlp.ts
src/sequenceView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-053 New analyzer folder from scratch

---

package.json
src/sequence.ts
src/sequenceView.ts

VSCODE-NLP-055 Added recursive and inactive passes to sequence editor

---

package.json
src/analyzer.ts
src/dirfuncs.ts
src/extension.ts
src/logfile.ts
src/sequence.ts
src/sequenceView.ts
src/visualText.ts

VSCODE-NLP-056 Added one level of folders to sequence

---

src/logView.ts
src/logfile.ts
src/sequence.ts
src/visualText.ts

VSCODE-NLP-057 Fix logging click button bug

---

package.json
src/extension.ts
src/helpView.ts
src/logView.ts

VSCODE-NLP-059 Help webview - beta

---

package.json
src/command.ts

VSCODE-NLP-060 Added legacy help link to NLP++ editor window menu

---

src/dirfuncs.ts
src/visualText.ts

VSCODE-NLP-061 Fixed problem with state file saving

---

src/sequence.ts
syntaxes/kb.tmLanguage.json

VSCODE-NLP-062 bug fix to the kb lexer & pass insert AFTER selected pass

---

package.json
src/textView.ts

VSCODE-NLP-063 Add existing text to textview

---

package.json

VSCODE-NLP-065 changes not included in last pull request 064

---

package.json
src/sequence.ts
src/sequenceView.ts

VSCODE-NLP-066 Insert pass bugs fixed and added display final tree

---

package.json
src/nlp.ts
src/status.ts

VSCODE-NLP-067 new log files off/on choice in status bar; label fixes

---

snippets/nlp.json
src/logfile.ts
src/status.ts

VSCODE-NLP-068 Added blt to highlighting logic, corrected snippet

---

src/logfile.ts
syntaxes/txxt.tmLanguage.json

VSCODE-NLP-069 Highlight unbuilt fired rules

---

src/sequence.ts

VSCODE-NLP-070 fix sequence bugs

---

package.json
src/logfile.ts
src/sequenceView.ts

VSCODE-NLP-071 context sensitive pass sequence menu and icon items

---

src/nlp.ts

VSCODE-NLP-072 Added refresh sequence after each run

---

src/logfile.ts

VSCODE-NLP-072 Bug fix for parsing log files.

---

src/dirfuncs.ts
src/logfile.ts
src/nlp.ts
src/status.ts

VSCODE-NLP-074 Add status bar fired/built mode

---

snippets/nlp.json

VSCODE-NLP-075 Full function snippets for nlp++

---

package.json
src/logView.ts
src/nlp.ts

VSCODE-NLP-076 Handle syntax error display better and fixed mouse overs

---

package.json
src/logfile.ts

VSCODE-NLP-077 fix highlight bug and missing icon

---

src/sequence.ts

VSCODE-NLP-079 Moves txxt and kb files with sequence pass move

---

package.json
src/command.ts
src/nlp.ts
src/sequenceView.ts

VSCODE-NLP-082 Add selected text search in nlp files

---

package.json
snippets/nlp.json
src/analyzer.ts
src/logfile.ts
src/sequenceView.ts
src/textView.ts

VSCODE-NLP-083 Added generate rule to *.txt files

---

package.json
src/outputView.ts
src/sequence.ts

VSCODE-NLP-084 display orphan passes in outputView

---

package.json

VSCODE-NLP-085 remove vsocde from dependencies for compilation

---

package.json
src/logfile.ts
src/sequenceView.ts
syntaxes/seq.tmLanguage.json

VSCODE-NLP-086 Misc fixes

---

src/logView.ts
src/nlp.ts
src/outputView.ts
src/textFile.ts

VSCODE-NLP-087 err.log and dbg.log will now open

---

src/findFile.ts

VSCODE-NLP-088 Searches now can include non-alpha characters

---

src/status.ts

VSCODE-NLP-089 Log generation messages fixed

---

package.json

VSCODE-NLP-092 Changes for publishing in Microsoft Marketplace

---

README.md

VSCODE-NLP-093 Update README.md

---

README.md
package.json

VSCODE-NLP-094 README.md and version update

---

README.md
package.json

VSCODE-NLP-095 Updated the Readme to include sample analyzer information

---

README.md
package.json

VSCODE-NLP-096 Updating README.md

---

package.json

VSCODE-NLP-097 package.json changes

---

.vscodeignore
package.json

VSCODE-NLP-098 Changes for packaging extension

---

README.md
package.json
src/analyzerView.ts
src/findView.ts
src/textView.ts

VSCODE-NLP-099 Commented out title change for treeviews

---

.vscodeignore
CHANGELOG.md
package.json
resources/vs_nlp-icon-theme.json

VSCODE-NLP-101 icon paths corrected

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-102 Preview = true

---

.vscodeignore
CHANGELOG.md
README.md
package.json

VSCODE-NLP-103 Attention notice in readme and ignore fix

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-104 Adding missing dependency and removing unneeded ones

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-107 Remove preview mode and attention text in README.md

---

CHANGELOG.md
README.md
dist/dirfuncs.js
package.json
src/dirfuncs.ts

VSCODE-NLP-108 Fixed delete directory bug

---

.vscodeignore
CHANGELOG.md
README.md
package.json

VSCODE-NLP-109 Added rimraf to vsce package

---

.vscodeignore
CHANGELOG.md
README.md
package.json

VSCODE-NLP-110 Fixing missing node modules

---

.vscodeignore
CHANGELOG.md
README.md
package.json

VSCODE-NLP-111 Adding a missing node module

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-112 Adding animated gif for loading analyzers and running

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-113 Rule fired fixed for mixed highlighting

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-114 Fixing finding rule fired logic

---

.vscode/settings.json
CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/analyzerView.ts
src/dirfuncs.ts
src/findFile.ts
src/findView.ts
src/jsonState.ts
src/logView.ts
src/logfile.ts
src/nlp.ts
src/outputView.ts
src/sequence.ts
src/sequenceView.ts
src/status.ts
src/textFile.ts
src/textView.ts
src/visualText.ts

Signed-off-by: David de Hilster <david.dehilster@lexisnexisrixk.com>

VSCODE-NLP-115 path to fspath to work on windows and linux

---

CHANGELOG.md
README.md
package.json
src/nlp.ts

VSCODE-NLP-116 Fixed command line call to nlp.exe

---

.vscodeignore
CHANGELOG.md
README.md
package.json
src/nlp.ts

VSCODE-NLP-117 fixing packaging

---

CHANGELOG.md
README.md
package.json
src/sequence.ts
src/sequenceView.ts

VSCODE-NLP-118 Fixing sequence editing problems

---

CHANGELOG.md
README.md
package.json
src/outputView.ts

VSCODE-NLP-119 fixed crash when doing a textview load

---

README.md

VSCODE-NLP-120 Updated README to include Linux, Windows, MacOS

---

package.json
resources/dark/dnar-grayed.svg
resources/dark/dnar.svg
resources/light/dnar-grayed.svg
resources/light/dnar.svg
src/sequence.ts
src/sequenceView.ts
src/visualText.ts

VSCODE-NLP-123 more version 1 and pass properties fixes

---

src/dirfuncs.ts
src/nlp.ts
src/visualText.ts

VSCODE-NLP-124 Fixing version 1

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-125 Version one release with the nlp-engine built in

---

package.json
src/command.ts
src/nlp.ts

VSCODE-NLP-126 add duplicate line to rule editor

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-127 Update version information

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-128 add new nlp-engine with empty folders

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-128 Change version to fix vscode extension version 1.0.7

---

CHANGELOG.md
README.md
package.json
syntaxes/nlp.tmLanguage.json

VSCODE-NLP-129 fixed colorizer for rule rewrite line

---

CHANGELOG.md
README.md
package.json
syntaxes/nlp.tmLanguage.json

VSCODE-NLP-130 More lexer fixes

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/logView.ts
src/nlp.ts
src/textView.ts

VSCODE-NLP-131 Added processing of texts inside a folder

---

package.json
src/analyzer.ts
src/dirfuncs.ts
src/outputView.ts
src/sequence.ts
src/sequenceView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-133 Rename and delete log directory with file change

---

package.json
src/sequence.ts
src/sequenceView.ts

VSCODE-NLP-134 Add different tokenizers

---

CHANGELOG.md
README.md
package.json
src/sequence.ts
src/sequenceView.ts
src/textFile.ts

VSCODE-NLP-136 Fix sequence one line bug & allow multiple selects

---

CHANGELOG.md
README.md
package.json
src/logfile.ts
src/sequence.ts
src/sequenceView.ts
src/textFile.ts

VSCODE-NLP-137 Changed .pat files to .nlp

---

.vscodeignore
package.json
src/visualText.ts

VSCODE-NLP-139 Fetch nlp-engine from latest github release

---

package-lock.json

VSCODE-NLP-140 sync package-lock.json and package.json

---

CHANGELOG.md
README.md

VSCODE-NLP-142 Update versions in readme and changelog

---

src/visualText.ts

VSCODE-NLP-144 Fix bug for loading analyzer after downloading

---

src/findFile.ts
src/findView.ts
src/sequence.ts
src/sequenceView.ts
src/textView.ts

VSCODE-NLP-146 Fixed search bug

---

src/findView.ts

VSCODE-NLP-147 Not found message

---

src/analyzer.ts

VSCODE-NLP-148 Analyzer types when creating a new analyzer

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-149 Update version numbers

---

CHANGELOG.md
README.md
package.json
src/status.ts
src/visualText.ts

VSCODE-NLP-150 Check nlp-version and update if needed or asked

---

package.json
src/logfile.ts

VSCODE-NLP-151 _xALPHA for capitalized alphas in rule generate

---

CHANGELOG.md
README.md
package.json
syntaxes/nlp.tmLanguage.json

VSCODE-NLP-152 Lexer improvements

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/status.ts
src/visualText.ts

VSCODE-NLP-153 Added checking version of visualtext files separately

---

src/visualText.ts

VSCODE-NLP-154 Fixed version checking for nlpengine.zip on startup

---

CHANGELOG.md
README.md
package.json
resources/vs_nlp-icon-theme.json
src/logfile.ts
src/outputView.ts
src/sequenceView.ts
src/textFile.ts

VSCODE-NLP-155 ana.log files to ana.tree files

---

package.json
resources/dark/list-tree.svg
resources/dark/tree.svg
resources/light/list-tree.svg
resources/light/tree.svg
resources/vs_nlp-icon-theme.json

VSCODE-ECL-155 changed tree icon to be a real tree

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/visualText.ts

VSOCDE-NLP-156 nlp.exe now in one place

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/outputView.ts

VSCODE-NLP-157 fixed orphan listing

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/sequenceView.ts
src/status.ts
src/visualText.ts

VSCODE-NLP-159 fix problem with nlp-engine updating into older install directory

---

CHANGELOG.md
README.md
package.json
src/status.ts

VSCODE-NLP-160 Add VSCode NLP Extension to status bar

---

CHANGELOG.md
README.md
package.json
src/outputView.ts

VSCODE-NLP-161 Ouput file listing to list all but tree and kbb files

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-162 Fixed autogenerate rule

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/jsonState.ts
src/nlp.ts
src/textFile.ts

VSCODE-NLP-163 Added first version progress bar

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/command.ts
src/dirfuncs.ts
src/nlp.ts
src/textFile.ts

VSCODE-NLP-164 Added comment / uncomment lines

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-165 Updated Readme.md

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-166 Fix rule generation bug

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-167 Fix selection range bug

---

CHANGELOG.md
README.md
package.json
src/helpView.ts

VSCODE-NLP-168 Help no longer needs to highlight entire word

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-169 Duplicate lines fix

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/nlp.ts

VSCODE-NLP-170 Display syntax errors in log after analyzing

---

CHANGELOG.md
README.md
package.json
resources/dark/x-box.svg
resources/light/x-box.svg
src/analyzerView.ts
src/nlp.ts
src/sequenceView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-174 Adding delete log files for all analyzers in folder

---

CHANGELOG.md
README.md
package.json
src/command.ts

VSCODE-NLP-176 Add online function help

---

CHANGELOG.md
package-lock.json
package.json
src/logfile.ts
src/visualText.ts

VSCODE-NLP-178 Save selected tree files to temp

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/command.ts
src/findFile.ts
src/findView.ts
src/nlp.ts
src/sequenceView.ts

VSCODE-NLP-179 Add quickie find function

---

CHANGELOG.md
README.md
package.json
src/findFile.ts

VSCODE-NLP-180 Fixing bugs with Search Function

---

CHANGELOG.md
README.md
package-lock.json
package.json
resources/dark/document.svg
src/analyzerView.ts
src/dirfuncs.ts
src/outputView.ts
src/sequenceView.ts
src/textView.ts

VSCODE-NLP-181 Add log deletion option on TextView

---

CHANGELOG.md
README.md
package.json
src/extension.ts
src/visualText.ts

VSCODE-NLP-183 initialization messages now go to LOGGING pane

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-184 Fix delete all logs in TextView

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/command.ts
src/nlp.ts
src/sequenceView.ts

VSCODE-NLP-185 Add sequence number display for nlp file

---

CHANGELOG.md
README.md
package.json
src/sequenceView.ts

VSCODE-NLP-186 Added uri to non-sequence nlp file sequence number lookup

---

CHANGELOG.md
README.md
package.json
snippets/nlp.json
src/command.ts
src/logfile.ts

VSCODE-NLP-212 Various issues fixed

---

README.md
package.json

VSCODE-NLP-213 Added Quick Video Guides to README.md

---

README.md
package.json

VSCODE-NLP-214 Added link to README.md

---

CHANGELOG.md
README.md
package.json
src/dirfuncs.ts
src/visualText.ts

VSCODE-NLP-215 Fixes to new empty analyzer folder

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-216 Now handles utf8 characters

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-217 Download nlp.exe and accompanying lib files

---

CHANGELOG.md
README.md
package.json
src/nlp.ts

VSCODE-NLP-221 Quick fix to reformat rule one line

---

CHANGELOG.md
README.md
package.json
snippets/nlp.json

VSCODE-NLP-222 Fix rule 3 post snippet to have an @ sign

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-223 Security updates

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-224 Fixes for mac and linux

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-225 Second ICU file loading twice

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-226 added 3rd icu library file

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-227 bugs still with new 3rd file upload

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-228 Don't need three ICU libs after all

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-229 try and deal with nlp.exe doesn't execute

---

.vscode/settings.json
CHANGELOG.md
README.md
package.json
src/logfile.ts
syntaxes/txxt.tmLanguage.json

VSCODE-NLP-230 change light brackets to not conflict with wititext

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-232 Fixed bug in View selected tree

---

CHANGELOG.md
README.md
package.json
src/sequenceView.ts

VSCODE-NLP-233 Added change pass to Pattern type

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-234 fixed version bug with linux and mac

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/logfile.ts
src/nlp.ts
src/textFile.ts

VSCODE-NLP-236 Added Generate @PATH from tree

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts
src/textView.ts

VSCODE-NLP-237 Fixed numerous problems with fileOps

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-239 remove "_ROOT" from path - already there

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-240 Changed Highlight Texts to Highlight Matched Rules

---

CHANGELOG.md
README.md
package.json
src/outputView.ts

VSCODE-NLP-241 add output view trees and matches

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/outputView.ts
src/textView.ts
syntaxes/nlp.tmLanguage.json

VSCODE-NLP-242 Don't open text when analyzing, misc fixes

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-243 release number fix

---

CHANGELOG.md
README.md
package.json
src/logfile.ts

VSCODE-NLP-244 fixed Generate @Path bug

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/status.ts
src/visualText.ts

VSCODE-NLP-245 Added cancel analyzer during processing

---

CHANGELOG.md
README.md
package.json
src/sequence.ts
src/sequenceView.ts

VSCODE-NLP-247 Added character separation tokenizer chartok

---

CHANGELOG.md
README.md
package.json
src/textView.ts
syntaxes/kb.tmLanguage.json
syntaxes/tree.tmLanguage.json

VSCODE-NLP-248 lexer fixes

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/command.ts

VSCODE-NLP-249 added fold and unfold recursively

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts

VSCODE-NLP-250 Added duplicate analyzer in the same folder

---

CHANGELOG.md
README.md
package.json
src/command.ts

VSCODE-NLP-251 Fixed generate exact

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/outputView.ts
src/textView.ts

VSCODE-NLP-252 Fix cancel strings all over

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-253 Fixed version log reporting

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-254 Added tutorial links to README.md

---

README.md
package.json
src/findFile.ts
src/logView.ts
src/logfile.ts
src/nlp.ts
src/sequence.ts
src/visualText.ts

VSCODE-NLP-256 fix for disappearing $ variables and substr to substring

---

CHANGELOG.md
README.md

VSCODE-NLP-258 updated readme and change

---

CHANGELOG.md
README.md
package.json
syntaxes/nlp.tmLanguage.json

VSCODE-NLP-259 Fixed lexer problems

---

.vscode/settings.json
CHANGELOG.md
README.md
package.json
syntaxes/nlp.tmLanguage.json

VSCODE-NLP-260 Color for rule attributes

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/logfile.ts
src/nlp.ts
src/sequenceView.ts

VSCODE-NLP-262 Added cross ref context menu items in nlp, tree, and txxt

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-263 Don't display Open Pass File for final.tree

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/command.ts
src/logView.ts
src/nlp.ts
src/sequence.ts
src/sequenceView.ts
src/status.ts
src/textFile.ts
src/treeFile.ts
syntaxes/txxt.tmLanguage.json

VSCODE-NLP-264 Added more context menu items, renamed logFile to treeFile

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-265 Restore highlight text from tree

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-266 update icu from 69 to 71

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/analyzerView.ts
src/fileOps.ts
src/findView.ts
src/sequence.ts
src/sequenceView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-267 Made .pat to .nlp more obvious and clean; misc fixes

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/textView.ts

VSCODE-NLP-268 Major fixes to the textview conext menu

---

CHANGELOG.md
README.md
package.json
syntaxes/kbb.tmLanguage.json
syntaxes/nlp.tmLanguage.json
syntaxes/tree.tmLanguage.json

VSCODE-NLP-269 Unicode fixes for colorizing

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/extension.ts
src/fileOps.ts
src/textView.ts

VSCODE-NLP-270 Added a KB View List

---

package.json
src/status.ts
src/textView.ts

VSCODE-NLP-272 Cleaning up context and title menus

---

CHANGELOG.md
README.md
package.json
syntaxes/kb.tmLanguage.json

VSCODE-NLP-273 Enhanced kb file colorization

---

CHANGELOG.md
README.md
package.json
src/nlp.ts

VSCODE-NLP-274 Logs off now produce no logs

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/analyzerView.ts
src/fileOps.ts
src/kbView.ts
src/outputView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-277 Added refresh treeviews array to fileops

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/nlp.ts
src/outputView.ts
src/visualText.ts

VSCODE-NLP-278 Fixes to json state file for analyzers

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/outputView.ts

VSCODE-NLP-279 Output files deletion error

---

CHANGELOG.md
README.md
package.json
snippets/nlp.json
src/textView.ts

VSCODE-NLP-280 Added new NLP++ struniquechars function to snippets

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-281 Updating vscode extension which was behind

---

CHANGELOG.md
README.md
package.json
src/kbView.ts

VSCODE-NLP-282 fix refresh kbView

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-283 removed redundant command in package.json

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-284 Added sort to dict files

---

CHANGELOG.md
README.md
package.json
src/nlp.ts

VSCODE-NLP-285 progress bar changes (still not done correctly)

---

CHANGELOG.md
README.md
package.json
resources/dark/cancel-button.svg
resources/light/cancel-button.svg
src/analyzerView.ts
src/dirfuncs.ts
src/fileOps.ts
src/logView.ts
src/nlp.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-286 File and folder properties

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts
src/visualText.ts

VSCODE-NLP-288 Fixed renaming

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-289 Fixed delete analyzer logs in TextView title bar

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-290 Fixed TextView delete logs icon

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-291 Added more keybindings to nlp and tree files

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
syntaxes/tree.tmLanguage.json

VSCODE-NLP-292 fixed duplicate bug and added num to tree lexer

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts

VSCODE-NLP-294 Added zzzend.txt to directory split

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts

VSCODE-NLP-295 Fixed new bug for delete log files for directories

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts
src/nlp.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-296 Added analyzer processing queue

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/helpView.ts

VSCODE-NLP-297 Added help for special variables with dollar signs

---

CHANGELOG.md
README.md
package.json
src/helpView.ts

VSCODE-NLP-298 Fixed online help for dollar sign files

---

CHANGELOG.md
README.md
package.json
src/kbView.ts

VSCODE-NLP-299 Added main.kb generated

---

CHANGELOG.md
README.md
package.json
src/nlp.ts

VSCODE-NLP-300 Added Analyzing done message

---

CHANGELOG.md
README.md
package.json
src/dirfuncs.ts
src/nlp.ts
src/sequenceView.ts
src/status.ts
src/textView.ts

VSCODE-NLP-302 Warn to turn off logging

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-303 Changed file count for asking user about logs

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-304 Fix analyze folder bug

---

CHANGELOG.md
README.md
src/status.ts
src/textView.ts

VSCODE-NLP-305 Status dev change fixed

---

CHANGELOG.md
README.md
package.json
src/dirfuncs.ts

VSCODE-NLP-306 Fixed file count for asking for log turn off

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/findView.ts
src/kbView.ts
src/logView.ts
src/outputView.ts
src/sequenceView.ts
src/textView.ts

NLP-ENGINE-308 Fixed all the refresh TreeViews

---

CHANGELOG.md
README.md
package.json
src/logView.ts

VSCODE-NLP-310 fixed logview list bug

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts
src/kbView.ts

VSCODE-NLP-311 Added merge dict files into all.dict

---

CHANGELOG.md
README.md
package.json
syntaxes/dict.tmLanguage.json

VSCODE-NLP-312 Changed dict file lexer to allow phrases

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts

VSCODE-NLP-313 Fixed final tree display from sequence title

---

.vscode/settings.json
CHANGELOG.md
README.md
dist/analyzer.js
src/analyzer.ts
src/analyzerView.ts
src/findView.ts
src/jsonState.ts
src/kbView.ts
src/logView.ts
src/nlp.ts
src/outputView.ts
src/sequenceView.ts
src/textView.ts
src/treeFile.ts
src/visualText.ts

VSCODE-NLP-316 fixed auto colorize

---

.vscodeignore
CHANGELOG.md
DOWNLOADWARNING.md
README.md
package.json
src/logView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-317 Warning advice for engine update fail

---

.vscodeignore
CHANGELOG.md
README.md
package.json

VSCODE-NLP-319 Version update

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/dirfuncs.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-321 Add move files to textView

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-322 replaced deleted load default analyzers

---

CHANGELOG.md
package.json
src/jsonState.ts
src/logView.ts

VSCODE-NLP-323 Json parse error logic

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/textView.ts

VSCODE-NLP-324 fixed arrow showing up when no folders

---

CHANGELOG.md
DOWNLOADHELP.html
README.md
UPDATERHELP.html
package.json
src/extension.ts
src/helpView.ts
src/logView.ts
src/visualText.ts

VSCODE-NLP-325 Enhancing error reporting in log view

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts

VSCODE-NLP-326 Fixed display of selected analyzer

---

.vscodeignore
CHANGELOG.md
README.md
package.json

VSCODE-NLP-327 included file in vsix file

---

CHANGELOG.md
README.md
package.json
src/helpView.ts
src/logView.ts
src/visualText.ts

VSCODE-NLP-328 Add title variable for displaying html files

---

CHANGELOG.md
README.md
package.json
src/logView.ts

VSCODE-NLP-329 had help functions switched

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-330 Open input directory bug fix

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/fileOps.ts
src/logView.ts
src/status.ts
src/visualText.ts

VSCODE-NLP-331 Complete overhaul of updater

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-332 Turned off debug flag in visualText.ts

---

CHANGELOG.md
README.md
package.json
src/status.ts
src/visualText.ts

VSCODE-NLP-333 Fixed status bar problems with new updater

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/analyzerView.ts
src/visualText.ts

VSCODE-NLP-334 Default analyzers to Example, warnings, and fixes

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts

VSCODE-NLP-335 fixed isConverting error

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/status.ts
src/visualText.ts

VSCODE-NLP-337 removed nlp engine path from NLP settings

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/visualText.ts

VSCODE-NLP-338 nlp.exe path fix

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-339 fix textview contextValue detection

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/visualText.ts

VSCODE-NLP-340 Bug fixes with paths broken recently

---

CHANGELOG.md
README.md
package.json
src/sequence.ts
src/sequenceView.ts

VSCODE-NLP-341 Added submenus to insert new and library passes

---

CHANGELOG.md
README.md
package.json
src/kbView.ts

VSCODE-NLP-343 explore kb dir

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/fileOps.ts
src/sequenceView.ts
src/visualText.ts

VSCODE-NLP-344 Fixed rename pat to nlp bug and more

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-345 Added fetch boost_filesystem

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-346 boost filesystem name for windows

---

CHANGELOG.md
README.md
package.json
src/logView.ts

VSCODE-NLP-347 Added updater debugger toggle

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-348 Turned update debugger off as default

---

CHANGELOG.md
README.md
package.json
src/sequenceView.ts
src/visualText.ts

VSCODE-NLP-349 Fixed filesystem download for linux & Mac, convert nlp fixed

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-350 Removed boost

---

CHANGELOG.md
README.md
package.json
src/fileOps.ts

VSCODE-NLP-351 fixed rename extension finally?

---

CHANGELOG.md
README.md
package.json
resources/dark/kbb-new.svg
resources/light/kbb-new.svg
src/kbView.ts

VSCODE-NLP-352 New version with kbb files being read by the NLP-ENGINE

---

CHANGELOG.md
README.md
src/analyzerView.ts
src/fileOps.ts
src/sequenceView.ts

VSCODE-NLP-353 Fix with analyzer converting flag

---

.vscodeignore
CHANGELOG.md
README.md
package.json
src/status.ts
src/visualText.ts

VSCODE-NLP-357 Fixing engine version tracking

---

CHANGELOG.md
README.md
package.json
src/kbView.ts
src/textView.ts

VSCODE-NLP-358 Add import KB files

---

CHANGELOG.md
README.md
package.json
snippets/nlp.json

VSCODE-NLP-359 bettered KB Global snippet

---

CHANGELOG.md
README.md
package.json
snippets/nlp.json
src/nlp.ts
src/outputView.ts
src/sequenceView.ts

VSCODE-NLP-360 Various improvements

---

CHANGELOG.md
README.md
package.json
src/outputView.ts

VSCODE-NLP-361 Added move file from output to kb directory

---

CHANGELOG.md
README.md
package.json
syntaxes/dict.tmLanguage.json

VSCODE-NLP-362 Fixed dict lexer

---

CHANGELOG.md
README.md
package.json
src/helpView.ts
src/outputView.ts
src/sequenceView.ts

VSCODE-NLP-363 Dict type in output, explore in sequence, and bug fixes.

---

CHANGELOG.md
README.md
package.json
src/textView.ts

VSCODE-NLP-364 Redisplay analyzer sequence when deleting log files

---

CHANGELOG.md
README.md
package.json
src/status.ts
src/visualText.ts

VSCODE-NLP-365 Fixed the updating once again

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-366 Bug fix to updater

---

CHANGELOG.md
README.md
package.json
resources/dark/kb-copyto.svg
resources/dark/text-copyto.svg
resources/light/kb-copyto.svg
resources/light/text-copyto.svg
src/analyzer.ts
src/analyzerView.ts
src/kbView.ts
src/logView.ts
src/outputView.ts
src/sequenceView.ts
src/status.ts
src/textView.ts
syntaxes/kbb.tmLanguage.json

VSCODE-NLP-367 Move to analyzer folder & improved user input descriptions

---

CHANGELOG.md
README.md
package.json
src/outputView.ts

VSCODE-NLP-368 Redisplay KB and Text views when copy to

---

CHANGELOG.md
README.md
package.json
resources/dark/dot.svg
resources/dark/right-blue.svg
resources/light/dot.svg
resources/light/right-blue.svg
src/logView.ts
src/nlp.ts

VSCODE-NLP-369 NLP Engine couts are now displayed in the logview

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/kbView.ts
src/nlp.ts
src/outputView.ts
src/sequenceView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-371 Various new features for analyzers and other views

---

.vscode/settings.json
CHANGELOG.md
README.md
package.json
src/sequence.ts
syntaxes/kbb.tmLanguage.json

VSCODE-NLP-372 Improved the kbb lexer

---

CHANGELOG.md
README.md
package.json
resources/dark/toggle.svg
resources/light/toggle.svg
snippets/nlp.json
src/kbView.ts

VSCODE-NLP-374 kb & dict toggle, new while snippets

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/kbView.ts
src/logView.ts
src/visualText.ts

VSCODE-NLP-375 Addressing issues

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/sequence.ts
src/textView.ts

VSCODE-NLP-376 duplicate line in dict, fixed import file from textview

---

CHANGELOG.md
README.md
package.json
src/treeFile.ts

VSCODE-NLP-378 Fixed generate rule from string

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-379 updated icu version to 72

---

CHANGELOG.md
README.md
package.json
src/kbView.ts
src/visualText.ts

VSCODE-NLP-380 Added dict and kb library files

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/outputView.ts

VSCODE-NLP-381 Move VisualText editor up or down in the analyzer view

---

CHANGELOG.md
README.md
package.json
src/kbView.ts

VSCODE-NLP-382 Warning if no kb library files

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-383 version

---

CHANGELOG.md
README.md
package.json
src/analyzer.ts
src/analyzerView.ts
src/visualText.ts

VSCODE-NLP-384 New analyzer now goes to selected folder, fixed list analyzer bug

---

CHANGELOG.md
README.md
package.json
snippets/nlp.json
src/analyzerView.ts
src/fileOps.ts
src/textView.ts

VSCODE-NLP-385 Rename analyzers and misc stuff

---

CHANGELOG.md
README.md
package.json
src/kbView.ts

VSCODE-NLP-389 Added new option to KB clean

---

CHANGELOG.md
README.md
package.json
src/outputView.ts
src/textView.ts
src/visualText.ts

VSCODE-NLP-390 Now can choose recursive analyzers

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts

VSCODE-NLP-391 Fixing adding new analyzer

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-392 Fix delete analyzer logs bug

---

CHANGELOG.md
README.md
package.json
src/analyzerView.ts
src/command.ts
src/kbView.ts
src/outputView.ts
src/sequenceView.ts

VSCODE-NLP-393 Added video help buttons to various viewers

---

CHANGELOG.md
README.md
package.json
src/logView.ts
src/nlp.ts

VSCODE-NLP-395 fixed syntax error display bug

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-396 updated version

---

CHANGELOG.md
README.md
package.json
src/visualText.ts

VSCODE-NLP-397 fixed updating engine infinite loop

---

CHANGELOG.md
README.md
package.json

VSCODE-NLP-398 version stupid!

---

CHANGELOG.md
README.md
package.json
src/sequence.ts

VSCODE-NLP-399 active status moves with move

---

CHANGELOG.md
README.md
package.json
src/status.ts
src/visualText.ts

VSCODE-NLP-400 fix import files in textview

---

CHANGELOG.md
README.md
package.json
src/treeFile.ts

VSCODE-NLP-401 Fixed highlighting bug

---

CHANGELOG.md
README.md
package.json
resources/dark/yield.svg
resources/light/yield.svg
src/logView.ts
src/sequence.ts
src/sequenceView.ts
src/textFile.ts
src/textView.ts

VSCODE-NLP-402 yield sign, duplicate pass number, other misc

---

CHANGELOG.md
README.md
package.json
src/sequence.ts
src/visualText.ts

VSCODE-NLP-405 choose sister passes now list in order in sequence for selection

---

CHANGELOG.md
README.md
package.json
src/sequenceView.ts

VSCODE-NLP-408 open new file when renaming pass in sequence

---

CHANGELOG.md
README.md
package.json
src/nlp.ts
src/treeFile.ts

VSCODE-NLP-409 Opening files "to the side" for trees, etc

---

CHANGELOG.md
README.md
package.json
src/textView.ts
src/visualText.ts
tsconfig.json

VSCODE-NLP-411 Text rename opens new file name

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/nlp.ts
src/sequenceView.ts

VSCODE-NLP-412 Added Copy context from pass above

---

CHANGELOG.md
README.md
package.json
src/command.ts
src/nlp.ts

VSCODE-NLP-461 Retooled reformat rule, added user comments, one-line, and parens formatting
